name: 'Standard Release'
inputs:
  github-token:
    required: true
  asset-path:
    description: 'A single file path or a glob pattern (e.g., dist/*)'
    required: false

runs:
  using: "composite"
  steps:
    - name: Check if repo is already checked out
      id: check-repo
      run: |
        if git rev-parse --is-inside-work-tree > /dev/null 2>&1; then
        echo "exists=true" >> "$GITHUB_OUTPUT"
        else
        echo "exists=false" >> "$GITHUB_OUTPUT"
        fi
      shell: bash
    - name: Checkout Repository
      if: steps.check-repo.outputs.exists != 'true'
      uses: actions/checkout@v6
      with:
        fetch-depth: 0
        token: ${{ inputs.github-token }}
    - name: Setup environment
      id: setup
      run: |
        REPO_NAME="${{ github.event.repository.name }}"

        # Remove 'ansible-role-'if it's at the start
        ROLE_NAME="${REPO_NAME#ansible-role-}"

        # Create a unique path in the runner's temp folder
        export RELEASE_PATH="${{ runner.temp }}/release_artifacts"
        mkdir -p "$RELEASE_PATH"

        # Save variables to the step outputs
        echo "path=$RELEASE_PATH" >> "$GITHUB_OUTPUT"
        echo "role_name=$ROLE_NAME" >> "$GITHUB_OUTPUT"

        if ! [ -d doc ]; then
          echo "WARNING, creating documentation stub"
          mkdir doc
          echo "#+TITLE: Ansible role: ${ROLE_NAME}" >doc/index.org
        fi
      shell: bash
    - name: Extract full changelog
      uses: aardsoft/ci-actions/extract-full-changelog@master
      id: full-changelog
    - name: Build raw doc archive
      shell: bash
      id: raw-doc
      run: |
        tar czvf "${{ steps.setup.outputs.path }}/doc-org.tar.gz" -C doc .
    - name: Create role archive
      shell: bash
      id: role-archive
      run: |
        TAG=${GITHUB_REF#refs/tags/}

        if [ -f .pkg_meta ]; then
          . .pkg_meta
        fi
        # we want the changelog both in the tar and release artifacts
        cp "${{ steps.full-changelog.outputs.changelog-path }}" CHANGELOG.md
        cp "${{ steps.full-changelog.outputs.changelog-path }}" "${{ steps.setup.outputs.path }}/CHANGELOG.md"
        rm -f "${{ steps.full-changelog.outputs.changelog-path }}"

        echo "version: $TAG
        description: ${pkg_description}
        repository_name: ${pkg_repository_name:-${{ github.repository }}}
        repository_server: ${pkg_repository_server:-${{ github.server_url }}}
        name: ${{ steps.setup.outputs.role_name }}" > role-metadata.yml
        tar czvf "${{ steps.setup.outputs.path }}/${{ steps.setup.outputs.role_name }}-$TAG.tar.gz" \
        --exclude ./doc --exclude .gitignore --exclude .git --exclude .github  --exclude .pkg_meta --exclude README.org .
    - name: Build HTML documentation
      uses: aardsoft/ci-actions/build-org-doc@master
      id: org-doc
      with:
        github-token: ${{ inputs.github-token }}
        publish-directory: /tmp/org-doc
    - name: Pack HTML documentation
      shell: bash
      id: org-doc-pack
      run: |
        TAG=${GITHUB_REF#refs/tags/}
        tar czvf "${{ steps.setup.outputs.path }}/${{ steps.setup.outputs.role_name }}-doc-$TAG.tar.gz" -C /tmp/org-doc .
    - name: Extract Changelog
      uses: aardsoft/ci-actions/extract-changelog@master
      id: changelog
      with:
        github-token: ${{ inputs.github-token }}
    - name: Create GitHub Release
      shell: bash
      run: |
        gh release create ${{ github.ref_name }} \
          --title "Release ${{ github.ref_name }}" \
          --notes-file ${{ steps.changelog.outputs.changelog-path }} \
          ${{ steps.setup.outputs.path }}/*
          ${{ inputs.asset-path }}
      env:
        GH_TOKEN: ${{ inputs.github-token }}
